/*
 * Moonshine - a Lua virtual machine.
 *
 * Copyright (C) 2013 Gamesys Limited,
 * 10 Piccadilly, London W1J 0DD
 * Email: moonshine@gamesys.co.uk
 * http://moonshinejs.org
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
define(function(require,exports,module){

var shine=shine||{};
(function(a){a.EMPTY_OBJ={};a.EMPTY_ARR=[];a.gc={objects:[],arrays:[],collected:0,reused:0,cacheArray:function(a){a.length=0;this.arrays.push(a)},cacheObject:function(a){for(var c in a)a.hasOwnProperty(c)&&delete a[c];this.objects.push(a)},createArray:function(){this.arrays.length&&this.reused++;return this.arrays.pop()||[]},createObject:function(){this.objects.length&&this.reused++;return this.objects.pop()||{}},decrRef:function(b){b&&b instanceof a.Table&&void 0!==b.__shine.refCount&&0==--b.__shine.refCount&&
this.collect(b)},incrRef:function(b){b&&b instanceof a.Table&&void 0!==b.__shine.refCount&&b.__shine.refCount++},collect:function(b){if(void 0!==b&&null!==b){if(b instanceof Array)return this.cacheArray(b);if("object"==typeof b&&b.constructor==Object)return this.cacheObject(b);if(b instanceof a.Table&&void 0!==b.__shine.refCount){var c,f,h=b.__shine;c=0;for(f=h.keys.length;c<f;c++)this.decrRef(h.keys[c]);c=0;for(f=h.values.length;c<f;c++)this.decrRef(h.values[c]);c=0;for(f=h.numValues.length;c<f;c++)this.decrRef(h.numValues[c]);
this.cacheArray(h.keys);this.cacheArray(h.values);delete h.keys;delete h.values;this.cacheObject(h);delete b.__shine;for(c in b)b.hasOwnProperty(c)&&this.decrRef(b[c])}}}}})(shine||{});"use strict";shine=shine||{};shine.EventEmitter=function(){this._listeners={}};shine.EventEmitter.prototype._trigger=function(a,b){var c=this._listeners[a],f,h;if(c)for(h in(b||shine.EMPTY_OBJ)instanceof Array||(b=[b]),c)if(c.hasOwnProperty(h)&&(f=c[h].apply(this,b),void 0!==f&&!f))break};
shine.EventEmitter.prototype.on=function(a,b){this._listeners[a]||(this._listeners[a]=[]);this._listeners[a].push(b)};shine.EventEmitter.prototype.unbind=function(a,b){for(var c in this._listeners[a])this._listeners[a].hasOwnProperty(c)&&this._listeners[a][c]===b&&this._listeners[a].splice(c,1)};"object"==typeof module&&module.exports&&(module.exports.EventEmitter=shine.EventEmitter);"use strict";shine=shine||{};shine.FileManager=function(){shine.EventEmitter.call(this);this._cache={}};
shine.FileManager.prototype=new shine.EventEmitter;shine.FileManager.prototype.constructor=shine.FileManager;
shine.FileManager.prototype.load=function(a,b){function c(a,k){var c;e.constructor._isJson(a)?c=JSON.parse(a):e.constructor._isLuac(a)&&(c=e.constructor._parseLuac(a));c&&window.setTimeout(function(){k&&(e._cache[k]=c);e._onSuccess(k||"",c,b)},1);return!!c}function f(b){if(!c(b,a))throw Error("File contains non-parsable content: "+a);}function h(a){e._onError(a,b)}var e=this,l;switch(typeof a){case "string":c(a)||((l=this._cache[a])?window.setTimeout(function(){e._onSuccess(a,l,b)},1):shine.utils.get(a,
f,h));break;case "object":this._onSuccess("",a,b);break;default:throw new TypeError("Can't load object of unknown type");}};
shine.FileManager.prototype._onSuccess=function(a,b,c){var f,h;if("moonshine.package"==b.format){for(h in b.files)this._cache[h]=b.files[h];this._trigger("loaded-package",b);if(!(a=b.main))return;if(!(b=b.files[a]))throw new ReferenceError("The package's main reference does not point to a filename within the package");}f=new shine.File(a,b);this._onFileLoaded(f,function(){c(null,f)})};shine.FileManager.prototype._onFileLoaded=function(a,b){b()};shine.FileManager.prototype._onError=function(a,b){b(a)};
shine.FileManager._isJson=function(a){return/^({.*}|\[.*\])$/.test(a)};shine.FileManager._isLuac=function(a){return a.substr(0,5)==String.fromCharCode(27,76,117,97,81)};shine.FileManager._parseLuac=function(a){if(!shine.distillery)throw Error('Moonshine needs the distillery to parse Lua byte code. Please include "distillery.moonshine.js" in the page.');"ArrayBuffer"in window||console.warn("Browser does not support ArrayBuffers, this could cause unexpected results when loading binary files.");return(new shine.distillery.Parser).parse(a)};
shine.FileManager.prototype.dispose=function(){delete this._cache};"use strict";
(function(a){a.VM=function(b){a.EventEmitter.call(this);this.fileManager=new a.FileManager;this._env=b||{};this._coroutineStack=[];this._status=a.RUNNING;this._resumeStack=[];this._callbackQueue=[];this._coroutineStack=[];this._resetGlobals()};a.VM.prototype=new a.EventEmitter;a.VM.prototype.constructor=a.VM;a.RUNNING=0;a.SUSPENDING=1;a.SUSPENDED=2;a.RESUMING=3;a.DEAD=4;a.VM.prototype._resetGlobals=function(){var b=new a.Table;b.setMember(-1,"moonshine");this._globals=this._bindLib(a.lib);this._globals.arg=
b;for(var c in this._globals)this._globals.hasOwnProperty(c)&&this._globals[c]instanceof a.Table&&(this._globals["package"].loaded[c]=this._globals[c]);this._globals["package"].loaded._G=this._globals;for(c in this._env)this._env.hasOwnProperty(c)&&(this._globals[c]=this._env[c])};a.VM.prototype._bindLib=function(b){var c=a.gc.createObject(),f;for(f in b)b.hasOwnProperty(f)&&(c[f]=b[f]);return new a.Table(c)};a.VM.prototype.load=function(a,c,f){var h=this;this.fileManager.load(a,function(e,l){if(e)throw new URIError("Failed to load file: "+
a+" ("+e+")");h._trigger("file-loaded",l);(c||void 0===c)&&h.execute(f,l)})};a.VM.prototype.execute=function(b,c){var f=c?[c]:this._files,h,e;if(!f.length)throw Error("No files loaded.");for(h in f)if(f.hasOwnProperty(h)){c=f[h];if(!c.data)throw Error("Tried to execute file before data loaded.");e=this._thread=new a.Function(this,c,c.data,this._globals);this._trigger("executing",[e,b]);try{if(b){var l=a.lib.coroutine.wrap.call(this,e),n=function(){l();b.uiOnly&&l._coroutine.status!=a.DEAD&&window.setTimeout(n,
1)};n()}else e.call()}catch(k){a.Error.catchExecutionError(k)}}};a.VM.prototype.setGlobal=function(a,c){this._globals[a]=c};a.VM.prototype.getGlobal=function(a){return this._globals[a]};a.VM.prototype.suspend=function(){if(this._status!==a.RUNNING)throw Error("attempt to suspend a non-running VM");var b=this;this._status=a.SUSPENDING;this._resumeVars=void 0;window.setTimeout(function(){b._status==a.SUSPENDING&&(b._status=a.SUSPENDED)},1)};a.VM.prototype.resume=function(b){if(this._status!==a.SUSPENDED&&
this._status!==a.SUSPENDING)throw Error("attempt to resume a non-suspended VM");arguments.length&&void 0===b||(b=b||this._resumeVars);if(b&&!(b instanceof Array)){var c=a.gc.createArray();c.push(b);b=c}this._status=a.RESUMING;this._resumeVars=b;if(c=this._resumeStack.pop())try{c instanceof a.Coroutine?c.resume():c instanceof a.Closure?c._run():c()}catch(f){if(!((f||a.EMPTY_OBJ)instanceof a.Error)){var h=f.stack||"",f=new a.Error("Error in host call: "+f.message);f.stack=h;f.luaStack=h.split("\n")}f.luaStack||
(f.luaStack=a.gc.createArray());f.luaStack.push([c,c._pc-1]);a.Error.catchExecutionError(f)}if(this._status==a.RUNNING)for(;this._callbackQueue[0];)this._callbackQueue.shift()()};a.VM.prototype.dispose=function(){var b,c;for(c in this._files)this._files.hasOwnProperty(c)&&this._files[c].dispose();(b=this._thread)&&b.dispose();delete this._files;delete this._thread;delete this._globals;delete this._env;delete this._coroutineStack;this.fileManager.dispose();delete this.fileManager;a.Closure._graveyard.length=
0;a.Closure._current=void 0;a.Coroutine._graveyard.length=0};a.getCurrentVM=function(){var a;return(a=this.Closure._current)&&a._vm}})(shine||{});"use strict";
(function(a){a.Register=function(){this._items=a.gc.createArray()};a.Register._graveyard=[];a.Register.create=function(){return a.Register._graveyard.pop()||new a.Register(arguments)};a.Register.prototype.getLength=function(){return this._items.length};a.Register.prototype.getItem=function(a){return this._items[a]};a.Register.prototype.setItem=function(b,c){var f=this._items[b];a.gc.incrRef(c);a.gc.decrRef(f);this._items[b]=c};a.Register.prototype.set=function(a){var c,f=Math.max(a.length,this._items.length);
for(c=0;c<f;c++)this.setItem(c,a[c])};a.Register.prototype.push=function(){this._items.push.apply(this._items,arguments)};a.Register.prototype.clearItem=function(a){delete this._items[a]};a.Register.prototype.splice=function(a,c){this._items.splice.apply(this._items,arguments)};a.Register.prototype.reset=function(){for(var b=0,c=this._items.length;b<c;b++)a.gc.decrRef(this._items[b]);this._items.length=0};a.Register.prototype.dispose=function(){this._items.reset();this.constructor._graveyard.push(this)}})(shine||
{});"use strict";shine=shine||{};
shine.Closure=function(a,b,c,f,h){var e=this;this._vm=a;this._globals=f;this._file=b;this._data=c;this._upvalues=h||shine.gc.createArray();this._constants=c.constants;this._functions=c.functions;this._instructions=c.instructions;this._register=this._register||shine.Register.create();this._pc=0;this._localsUsedAsUpvalues=this._localsUsedAsUpvalues||shine.gc.createArray();this._funcInstances=this._funcInstances||shine.gc.createArray();this._localFunctions=shine.gc.createObject();e=this;a=function(){for(var a=
shine.gc.createArray(),b=0,k=arguments.length;b<k;b++)a.push(arguments[b]);return e.execute(a)};a._instance=this;a.dispose=function(){e.dispose.apply(e,arguments);delete this.dispose};return a};shine.Closure.prototype={};shine.Closure.prototype.constructor=shine.Closure;shine.Closure._graveyard=[];shine.Closure._current=void 0;shine.Closure.create=function(a,b,c,f,h){var e=shine.Closure._graveyard.pop();return e?shine.Closure.apply(e,arguments):new shine.Closure(a,b,c,f,h)};
shine.Closure.prototype.execute=function(a){var b=this;if(this._vm._status!=shine.RUNNING)this._vm._callbackQueue.push(function(){b.execute.call(b,a)});else{this._pc=0;this._params=shine.gc.createArray().concat(a);this._register.set(a.splice(0,this._data.paramCount));if(7==this._data.is_vararg){var c=shine.gc.createArray().concat(a),f=c.length,c=new shine.Table(c);c.setMember("n",f);this._register.push(c)}try{return this._run()}catch(h){throw(h||shine.EMPTY_OBJ)instanceof shine.Error||(c=h.stack||
"",h=new shine.Error("Error in host call: "+h.message),h.stack=c,h.luaStack=c.split("\n")),h.luaStack||(h.luaStack=shine.gc.createArray()),h.luaStack.push([this,this._pc-1]),h;}}};
shine.Closure.prototype._run=function(){var a,b;this.terminated=!1;this._vm._status==shine.RESUMING?this._vm._resumeStack.length?this._pc--:(this._vm._status=shine.RUNNING,a=this._vm._resumeVars,delete this._vm._resumeVars):shine.debug&&shine.debug._status==shine.RESUMING?shine.debug._resumeStack.length?this._pc--:shine.debug._setStatus(shine.RUNNING):(b=this._vm._coroutineRunning)&&b.status==shine.RESUMING&&(b._resumeStack.length?this._pc--:(b.status=shine.RUNNING,a=b._yieldVars));if(a){for(var c=
4*(this._pc-1),f=this._instructions[c+1],c=this._instructions[c+3],h=shine.gc.createArray(),e=0,l=a.length;e<l;e++)h.push(a[e]);if(0===c){l=h.length;for(e=0;e<l;e++)this._register.setItem(f+e,h[e]);this._register.splice(f+l)}else for(e=0;e<c-1;e++)this._register.setItem(f+e,h[e]);shine.gc.collect(h)}for(;void 0!==this._instructions[4*this._pc];){a=this._data.linePositions&&this._data.linePositions[this._pc];a=this._executeInstruction(this._pc++,a);if((b=this._vm._coroutineRunning)&&b.status==shine.SUSPENDING){b._resumeStack.push(this);
if(b._func._instance==this)return a=b._yieldVars,b.status=shine.SUSPENDED,shine.Coroutine._remove(),a;return}if(this._vm._status==shine.SUSPENDING&&!a){this._vm._resumeStack.push(this);return}if(shine.debug&&shine.debug._status==shine.SUSPENDING&&!a){shine.debug._resumeStack.push(this);return}if(void 0!==a)return this.terminated=!0,this.dispose(),a}this.terminated=!0;this.dispose()};
shine.Closure.prototype._executeInstruction=function(a,b){this.constructor._current=this;var c=4*a;return shine.operations.HANDLERS[this._instructions[c]].call(this,this._instructions[c+1],this._instructions[c+2],this._instructions[c+3])};shine.Closure.prototype.getConstant=function(a){if(null!==this._constants[a])return this._constants[a]};
shine.Closure.prototype.hasRetainedScope=function(){if(this._localsUsedAsUpvalues.length||this._upvalues.length)return!0;for(var a in this._funcInstances)if(this._funcInstances.hasOwnProperty(a)&&this._funcInstances[a].isRetained())return!0;return!1};
shine.Closure.prototype.dispose=function(a){if(a||!this.hasRetainedScope())delete this._vm,delete this._globals,delete this._file,delete this._data,delete this._functions,delete this._instructions,delete this._pc,shine.gc.collect(this._params),shine.gc.collect(this._localFunctions),delete this._params,delete this._constants,delete this._upvalues,this._register.reset(),this._funcInstances.length=0,this._localsUsedAsUpvalues.length=0,shine.Closure._graveyard.push(this)};"use strict";shine=shine||{};
shine.Function=function(a,b,c,f,h){this._vm=a;this._file=b;this._data=c||shine.gc.createObject();this._globals=f;this._upvalues=h||shine.gc.createArray();this._index=shine.Function._index++;this.instances=shine.gc.createArray();this._runCount=this._retainCount=0;this._convertInstructions()};shine.Function.prototype={};shine.Function.prototype.constructor=shine.Function;shine.Function._index=0;
shine.Function.prototype.getInstance=function(){return shine.Closure.create(this._vm,this._file,this._data,this._globals,this._upvalues)};shine.Function.prototype._compile=function(){var a=this._data,b,c,f;(f=a._compiled)||(f=a._compiled=shine.jit.compile(this));f&&(b=this,this.apply=function(h,e){c=shine.gc.createObject();c._vm=b._vm;c._globals=b._globals;c._upvalues=b._upvalues;c._constants=a.constants;c._functions=a.functions;c._localsUsedAsUpvalues=shine.gc.createArray();return f.apply(c,e)})};
shine.Function.prototype._convertInstructions=function(){var a=this._data.instructions||shine.gc.createArray(),b,c,f,h,e;if("ArrayBuffer"in window){if(a instanceof Int32Array)return;if(0==a.length||void 0===a[0].op){b=new ArrayBuffer(4*a.length);b=new Int32Array(b);b.set(a);this._data.instructions=b;return}b=new ArrayBuffer(16*a.length);b=new Int32Array(b)}else{if(0==a.length||"number"==typeof a[0])return;b=[]}c=0;for(f=a.length;c<f;c++)h=a[c],e=4*c,b[e]=h.op,b[e+1]=h.A,b[e+2]=h.B,b[e+3]=h.C;this._data.instructions=
b};shine.Function.prototype.call=function(a){var b=shine.gc.createArray(),c=arguments.length,f;for(f=1;f<c;f++)b.push(arguments[f]);return this.apply(a,b)};shine.Function.prototype.apply=function(a,b,c){a&&a instanceof Array&&!b&&(b=a,a=void 0);if(shine.jit.enabled&&2==++this._runCount)return shine.Closure._current=this.getInstance()._instance,this._compile(),this.apply.apply(this,arguments);try{return this.getInstance().apply(a,b)}catch(f){shine.Error.catchExecutionError(f)}};
shine.Function.prototype.toString=function(){return"function: 0x"+this._index.toString(16)};shine.Function.prototype.retain=function(){this._retainCount++};shine.Function.prototype.release=function(){!--this._retainCount&&this._readyToDispose&&this.dispose()};shine.Function.prototype.isRetained=function(){if(this._retainCount)return!0;for(var a in this.instances)if(this.instances.hasOwnProperty(a)&&this.instances[a].hasRetainedScope())return!0;return!1};
shine.Function.prototype.dispose=function(a){this._readyToDispose=!0;if(a){a=0;for(var b=this.instances.length;a<b;a++)this.instances[a].dispose(!0)}else if(this.isRetained())return!1;delete this._vm;delete this._file;delete this._data;delete this._globals;delete this._upvalues;delete this.instances;delete this._readyToDispose;return!0};"use strict";shine=shine||{};
shine.Coroutine=function(a){shine.EventEmitter.call(this);this._func=a.getInstance();this._index=shine.Coroutine._index++;this._started=!1;this._yieldVars=void 0;this._resumeStack=this._resumeStack||shine.gc.createArray();this.status=shine.SUSPENDED;shine.stddebug.write("[coroutine created]\n")};shine.Coroutine.prototype=new shine.EventEmitter;shine.Coroutine.prototype.constructor=shine.Function;shine.Coroutine._index=0;shine.Coroutine._graveyard=[];
shine.Coroutine.create=function(a){var b=shine.Coroutine._graveyard.pop();return b?(shine.Coroutine.apply(b,arguments),b):new shine.Coroutine(a)};shine.Coroutine._add=function(a){var b=shine.getCurrentVM();b._coroutineStack.push(b._coroutineRunning);b._coroutineRunning=a};shine.Coroutine._remove=function(){var a=shine.getCurrentVM();a._coroutineRunning=a._coroutineStack.pop()};
shine.Coroutine.prototype.resume=function(){var a,b,c=this._func._instance._vm;try{if(this.status==shine.DEAD)throw new shine.Error("cannot resume dead coroutine");shine.Coroutine._add(this);c&&c._status==shine.RESUMING?b=c._resumeStack.pop():shine.debug&&shine.debug._status==shine.RESUMING&&(b=shine.debug._resumeStack.pop());if(b)a=b instanceof shine.Coroutine?b.resume():b instanceof Function?b():this._func._instance._run();else if(this._started){this.status=shine.RESUMING;shine.stddebug.write("[coroutine resuming]\n");
if(arguments.length){var f=shine.gc.createArray();b=0;for(var h=arguments.length;b<h;b++)f.push(arguments[b]);this._yieldVars=f}else this._yieldVars=void 0;a=this._resumeStack.pop()._run()}else this.status=shine.RUNNING,shine.stddebug.write("[coroutine started]\n"),this._started=!0,a=this._func.apply(null,arguments);if(shine.debug&&shine.debug._status==shine.SUSPENDING){shine.debug._resumeStack.push(this);return}this.status=this._func._instance.terminated?shine.DEAD:shine.SUSPENDED;a&&a.unshift(!0)}catch(e){e.luaStack||
(e.luaStack=shine.gc.createArray()),e.luaStack.push([this._func._instance,this._func._instance._pc-1]),a=[!1,e],this.status=shine.DEAD}this.status==shine.DEAD&&(shine.Coroutine._remove(),shine.stddebug.write("[coroutine terminated]\n"),this._dispose());return a};shine.Coroutine.prototype.toString=function(){return"thread:"+(this._index?"0x"+this._index.toString(16):"[dead]")};
shine.Coroutine.prototype._dispose=function(){delete this._func;delete this._index;delete this._listeners;delete this._started;delete this._yieldVars;delete this.status;this._resumeStack.length=0;shine.Coroutine._graveyard.push(this)};"use strict";
(function(a){a.Table=function(b){var c=(b||a.EMPTY_OBJ)instanceof Array,f,h,e;b=b||a.gc.createObject();this.__shine=f=a.gc.createObject();f.type="table";f.index=++a.Table.count;f.keys=a.gc.createArray();f.values=a.gc.createArray();f.numValues=[void 0];for(e in b)if(b.hasOwnProperty(e)){var l;f=c?parseInt(e,10)+1:e;h=b[e];null===h&&(h=void 0);l="undefined"!==typeof getQualifiedClassName?"Object"==getQualifiedClassName(h)&&!(h instanceof a.Table)&&!(h instanceof a.Coroutine)&&!(h instanceof a.Function)&&
!(h instanceof a.Closure)||"Array"==getQualifiedClassName(h):"object"==typeof h&&h.constructor===Object||h instanceof Array;this.setMember(f,l?new a.Table(h):h)}};a.Table.count=0;a.Table.prototype.getMember=function(b){var c=typeof b,f,h;"string"!=c||"getMember"!=b&&"setMember"!=b||(c="object");switch(c){case "string":if(this.hasOwnProperty(b)&&void 0!==this[b])return this[b];break;case "number":if(0<b&&b==b>>0){c=this.__shine.numValues[b];if(void 0!==c)return c;break}default:if(c=this.__shine.keys.indexOf(b),
0<=c)return this.__shine.values[c]}if((f=this.__shine.metatable)&&(h=f.__index))switch(h.constructor){case a.Table:return h.getMember(b);case Function:case a.Function:return c=h.apply(this,[this,b]),c instanceof Array?c[0]:c}};a.Table.prototype.setMember=function(b,c){var f=this.__shine.metatable,h=typeof b,e=0<b&&b==b>>0,l,n,k;"string"!=h||"getMember"!=b&&"setMember"!=b||(h="object");switch(h){case "string":l=this[b];break;case "number":if(e){l=this.__shine.numValues[b];break}default:n=this.__shine.keys,
k=n.indexOf(b),l=-1==k?void 0:this.__shine.values[k],void 0===l&&a.gc.incrRef(b)}if(void 0===l&&f&&f.__newindex)switch(f.__newindex.constructor){case a.Table:return f.__newindex.setMember(b,c);case Function:return f.__newindex(this,b,c);case a.Function:return f.__newindex.apply(this,[this,b,c])[0]}switch(h){case "string":this[b]=c;break;case "number":if(e){this.__shine.numValues[b]=c;break}default:0>k&&(k=n.length,n[k]=b),this.__shine.values[k]=c}a.gc.incrRef(c);a.gc.decrRef(l)};a.Table.prototype.toString=
function(){var b;return this.constructor!=a.Table?"userdata":this.__shine&&(b=this.__shine.metatable)&&b.__tostring?b.__tostring.call(void 0,this)[0]:"table: 0x"+this.__shine.index.toString(16)}})(shine||{});"use strict";shine=shine||{};shine.Error=function(a){this.message=a};shine.Error.prototype=Object.create?Object.create(Error.prototype):Error();shine.Error.prototype.constructor=shine.Error;
shine.Error.catchExecutionError=function(a){if(a)throw(a||shine.EMPTY_OBJ)instanceof shine.Error&&(a.luaMessage||(a.luaMessage=a.message),a.message=a.luaMessage+"\n    "+a._stackToString()),a;};
shine.Error.prototype._stackToString=function(){var a=[],b,c,f,h,e,l,n,k;this.luaStack=this.luaStack||[];l=0;for(k=this.luaStack.length;l<k;l++)if(!this.luaStack[l-1]||this.luaStack[l][0]!==this.luaStack[l-1][0]||this.luaStack[l][1]!==this.luaStack[l-1][1])if("string"==typeof this.luaStack[l])a.push(this.luaStack[l]);else{b=this.luaStack[l][0];c=this.luaStack[l][1];if(!(f=b._data.sourceName)){if(h=this.luaStack[l+1]&&this.luaStack[l+1][0]){for(n in h._localFunctions)if(h._localFunctions[n]._data===
b._data){f=n;break}if(!f)for(n in h._upvalues)if(e=h._upvalues[n].getValue(),(e||shine.EMPTY_OBJ)instanceof shine.Function&&e._data===b._data){f=h._upvalues[n].name;break}}if(!f)for(n in b._globals)if((b._globals[n]||shine.EMPTY_OBJ)instanceof shine.Function&&b._globals[n]._data===b._data){f=n;break}}b._file.data.sourcePath?(h=b._file.url.match("^(.*)/.*?$"),h=(null===h?".":h[1]||"")+"/"+h,h=h.replace(/\/\.\//g,"/").replace(/\/.*?\/\.\.\//g,"/")):h=b._file.url;a.push((f||"function")+" ["+(h||"file")+
":"+(b._data.linePositions?b._data.linePositions[c]:"?")+"]")}return a.join("\n    ")};shine.Error.prototype.toString=function(){return"Lua run-time error: "+this.message};"use strict";shine=shine||{};shine.File=function(a,b){this.url=a;this.data=b};shine.File.prototype.dispose=function(){delete this.url;delete this.data};
(function(a){function b(a){return"_G"==a?this._globals:this._globals[a]}function c(d,g){var w;if(void 0===d)throw new a.Error("Attempt to index a nil value ("+g+" not present in nil)");w=d instanceof a.Table?d.getMember(g):"string"==typeof d&&a.lib.string[g]?a.lib.string[g]:d[g];this&&this._localFunctions&&w&&w instanceof a.Function&&(this._localFunctions[g]=w);return w}function f(d,g){var w=this._globals[d];a.gc.incrRef(g);a.gc.decrRef(w);this._globals[d]=g}function h(d,g,w){if(void 0===d)throw new a.Error("Attempt to index a missing field (can't set \""+
g+'" on a nil value)');d instanceof a.Table?d.setMember(g,w):d[g]=w}function e(){var d=new a.Table;d.__shine.refCount=0;return d}function l(d,g){if(void 0===d)throw new a.Error("Attempt to index a nil value ("+g+" not present in nil)");return d instanceof a.Table?d.getMember(g):"string"==typeof d&&a.lib.string[g]?a.lib.string[g]:d[g]}function n(a,d,g,b,m){d=256<=d?this.getConstant(d-256):this._register.getItem(d);g=256<=g?this.getConstant(g-256):this._register.getItem(g);d=k.call(this,d,g,b,m);this._register.setItem(a,
d)}function k(d,g,w,b){var m=a.utils.coerceToNumber,k;if(d&&d instanceof a.Table&&(k=d.__shine.metatable)&&(b=k.getMember(w))||g&&g instanceof a.Table&&(k=g.__shine.metatable)&&(b=k.getMember(w)))return b.apply(null,[d,g],!0)[0];"number"!=typeof d&&(d=m(d,"attempt to perform arithmetic on a %type value"));"number"!=typeof g&&(g=m(g,"attempt to perform arithmetic on a %type value"));return b(d,g)}function p(a,d){return a+d}function q(a,d){return a-d}function x(a,d){return a*d}function z(a,d){return a/
d}function r(a,d){var g,b;if(0===d||-Infinity===d||Infinity===d||window.isNaN(a)||window.isNaN(d))return NaN;g=Math.abs(a)%(b=Math.abs(d));0>a*d&&(g=b-g);0>d&&(g*=-1);return g}function y(d){var g,b;if(d&&d instanceof a.Table&&(g=d.__shine.metatable)&&(b=g.getMember("__unm")))return g=a.gc.createArray(),g.push(d),b.apply(null,g,!0)[0];"number"!=typeof d&&(d=a.utils.coerceToNumber(d,"attempt to perform arithmetic on a %type value"));return-d}function s(d){var g,b;if(void 0==d)throw new a.Error("attempt to get length of a nil value");
if(d instanceof a.Table)return a.lib.table.getn(d);if("object"==typeof d){g=0;for(b in d)d.hasOwnProperty(b)&&g++;return g}return d.length}function d(d,g){var b=d&&d instanceof a.Table&&(t=d.__shine.metatable)&&(q=t.getMember("__concat")),m=a.utils.coerceToString,k,c,p,t,q,e;c=0;for(p=g.length;c<p;c++)k=g[c],void 0!==k&&k instanceof a.Table&&(t=k.__shine.metatable)&&(q=t.getMember("__concat"))||(q=b)?(e=a.gc.createArray(),e.push(k,d),d=q.apply(null,e,!0)[0]):(d=m(d,"attempt to concatenate a %type value"),
k=m(k,"attempt to concatenate a %type value"),d=k+d);return d}function g(d,g){var b,m,k;return d!==g&&d&&d instanceof a.Table&&(g||a.EMPTY_OBJ)instanceof a.Table&&(b=d.__shine.metatable)&&(m=g.__shine.metatable)&&b===m&&(k=b.getMember("__eq"))?(b=a.gc.createArray(),b.push(d,g),!!k.apply(null,b,!0)[0]):d===g}function m(a,d,g,b,m){d=256<=d?this.getConstant(d-256):this._register.getItem(d);g=256<=g?this.getConstant(g-256):this._register.getItem(g);t(d,g,b,m)!=a&&this._pc++}function t(d,g,b,m){var k=
"object"!=typeof d&&typeof d||d instanceof a.Table&&"table"||"userdata",c="object"!=typeof g&&typeof g||g instanceof a.Table&&"table"||"userdata",p,t,q;if(k!==c)throw new a.Error("attempt to compare "+k+" with "+c);if("table"==k){if((t=d.__shine.metatable)&&(q=g.__shine.metatable)&&t===q&&(p=t.getMember(b)))return b=a.gc.createArray(),b.push(d,g),p.apply(null,b,!0)[0];throw new a.Error("attempt to compare two table values");}return m(d,g)}function E(a,d){return a<d}function F(a,d){return a<=d}function G(d,
g,b){var m=a.gc.createArray(),k,c,p,t;this._vm._status==a.RESUMING?p=this._vm._resumeStack.pop():a.debug&&a.debug._status==a.RESUMING&&(p=a.debug._resumeStack.pop());if(p)p instanceof a.Coroutine?(c=p.resume())&&c.shift():c=p instanceof a.Closure?p._run():p();else if((k=this._vm._coroutineRunning)&&k.status==a.RESUMING)p=k._resumeStack.pop(),c=p._run();else{var q=[];if(0===g)for(g=this._register.getLength(),m=d+1;m<g;m++)q.push(this._register.getItem(m));else for(m=0;m<g-1;m++)q.push(this._register.getItem(d+
m+1));m=q}p||(c=this._register.getItem(d),c=H.call(this,c,m));a.gc.collect(m);if(this._vm._status==a.SUSPENDING)void 0!==c&&void 0===this._vm._resumeVars&&(this._vm._resumeVars=c instanceof Array?c:[c]);else if(c&&c instanceof Array||(c=[c]),!(k=this._vm._coroutineRunning)||k.status!=a.SUSPENDING)if(0===b){b=c.length;for(k=0;k<b;k++)this._register.setItem(d+k,null==(t=c[k])?void 0:t);this._register.splice(d+b)}else for(k=0;k<b-1;k++)this._register.setItem(d+k,null==(t=c[k])?void 0:t)}function H(d,
g){var b,m;if(void 0!==d)if(d.apply)b=d.apply(null,g);else if(d instanceof a.Table&&(b=d.__shine.metatable)&&(m=b.getMember("__call"))&&m.apply)g.unshift(d),b=m.apply(null,g,!0);else throw new a.Error("Attempt to call non-function");else throw new a.Error("Attempt to call a nil value");return b}function I(d,g){var b=d.apply(void 0,g),m;b&&b instanceof Array||(m=a.gc.createArray(),m.push(b),b=m);return b}function J(a){return this._register.getItem(a)}function K(a){this._register.clearItem(a)}function D(a,
d,g){for(var b=0,m=this._localsUsedAsUpvalues.length;b<m;b++){var k=this._localsUsedAsUpvalues[b];k&&k.registerIndex>=a&&(k.upvalue.value=d.call(this,k.registerIndex),k.upvalue.open=!1,this._localsUsedAsUpvalues.splice(b--,1),m--,g&&g.call(this,k.registerIndex))}}function B(d,g,b,m){var k=a.gc.createArray(),c,p,t,q,e,h;e=0;for(h=g.length;e<h;e+=4)c=g[e],p=g[e+1],t=g[e+2],q=g[e+3],k.push((c?A:v).call(this,d,e/4,p,t,q,b,m));return k}function L(a){return this._register.getItem(a)}function u(a,d){this._register.setItem(a,
d)}function v(d,g,b,m,k,c,p){var t=this,q;k=0;for(var e=this._localsUsedAsUpvalues.length;k<e;k++)if(b=this._localsUsedAsUpvalues[k],b.registerIndex===m){q=b.upvalue;break}q||(q={open:!0,getValue:function(){return this.open?c.call(t,m):this.value},setValue:function(d){this.open?p.call(t,m,d):(a.gc.incrRef(d),a.gc.decrRef(this.value),this.value=d)},name:this._functions[d].upvalues?this._functions[d].upvalues[g]:"(upvalue)"},this._localsUsedAsUpvalues.push({registerIndex:m,upvalue:q}));return q}function A(a,
d,g,b,m){var k=this;return{getValue:function(){return k._upvalues[b].getValue()},setValue:function(a){k._upvalues[b].setValue(a)},name:this._upvalues[b].name}}a.operations={};a.gc.decrRef.bind(a.gc);a.gc.collect.bind(a.gc);a.gc.createArray.bind(a.gc);a.operations.HANDLERS=[function(d,g){var b=this._register.getItem(g),m,k;this._register.setItem(d,b);if(this._data.locals&&b&&b instanceof a.Function)for(k=this._data.locals.length-1;0<=k;k--)m=this._data.locals[k],m.startpc==this._pc-1&&(this._localFunctions[m.varname]=
b)},function(a,d){this._register.setItem(a,this.getConstant(d))},function(a,d,g){this._register.setItem(a,!!d);g&&this._pc++},function(a,d){for(var g=a;g<=d;g++)this._register.setItem(g,void 0)},function(a,d){var g=void 0===this._upvalues[d]?void 0:this._upvalues[d].getValue();this._register.setItem(a,g)},function(a,d){d=this.getConstant(d);this._register.setItem(a,b.call(this,d))},function(a,d,g){d=this._register.getItem(d);g=256<=g?this.getConstant(g-256):this._register.getItem(g);this._register.setItem(a,
c.call(this,d,g))},function(a,d){var g=this.getConstant(d),b=this._register.getItem(a);f.call(this,g,b)},function(a,d){this._upvalues[d].setValue(this._register.getItem(a))},function(a,d,g){a=this._register.getItem(a);d=256<=d?this.getConstant(d-256):this._register.getItem(d);g=256<=g?this.getConstant(g-256):this._register.getItem(g);h.call(this,a,d,g)},function(a,d,g){this._register.setItem(a,e())},function(a,d,g){d=this._register.getItem(d);g=256<=g?this.getConstant(g-256):this._register.getItem(g);
this._register.setItem(a+1,d);this._register.setItem(a,l(d,g))},function(a,d,g){n.call(this,a,d,g,"__add",p)},function(a,d,g){n.call(this,a,d,g,"__sub",q)},function(a,d,g){n.call(this,a,d,g,"__mul",x)},function(a,d,g){n.call(this,a,d,g,"__div",z)},function(a,d,g){n.call(this,a,d,g,"__mod",r)},function(a,d,g){n.call(this,a,d,g,"__pow",Math.pow)},function(a,d){d=this._register.getItem(d);this._register.setItem(a,y(d))},function(a,d){this._register.setItem(a,!this._register.getItem(d))},function(a,d){d=
this._register.getItem(d);this._register.setItem(a,s(d))},function(a,g,b){var m=this._register.getItem(b),k=[];for(b-=1;b>=g;b--)k.push(this._register.getItem(b));this._register.setItem(a,d(m,k))},function(a,d){this._pc+=d},function(d,a,b){a=256<=a?this.getConstant(a-256):this._register.getItem(a);b=256<=b?this.getConstant(b-256):this._register.getItem(b);g(a,b)!=d&&this._pc++},function(a,d,g){m.call(this,a,d,g,"__lt",E)},function(a,d,g){m.call(this,a,d,g,"__le",F)},function(d,g,b){d=this._register.getItem(d);
a.utils.coerceToBoolean(d)!==!!b&&this._pc++},function(d,g,b){g=this._register.getItem(g);a.utils.coerceToBoolean(g)===!!b?this._register.setItem(d,g):this._pc++},G,function(d,a){return G.call(this,d,a,0)},function(d,g){var b=a.gc.createArray(),m,k;if(0===g)for(m=this._register.getLength(),k=d;k<m;k++)b.push(this._register.getItem(k));else for(k=0;k<g-1;k++)b.push(m=this._register.getItem(d+k)),a.gc.incrRef(m);D.call(this,0,J,K);this.dead=!0;return b},function(d,a){var g=this._register.getItem(d+
2),b=this._register.getItem(d+1),m=this._register.getItem(d)+g,g=g/Math.abs(g);this._register.setItem(d,m);if(1===g&&m<=b||1!==g&&m>=b)this._register.setItem(d+3,m),this._pc+=a},function(d,a){this._register.setItem(d,this._register.getItem(d)-this._register.getItem(d+2));this._pc+=a},function(d,g,b){g=a.gc.createArray();var m,k;g.push(this._register.getItem(d+1),this._register.getItem(d+2));g=I(this._register.getItem(d),g);for(k=0;k<b;k++)this._register.setItem(d+k+3,g[k]);void 0!==(m=g[0])?this._register.setItem(d+
2,m):this._pc++},function(d,a,g){a=a||this._register.getLength()-d-1;var b;for(b=0;b<a;b++)this._register.getItem(d).setMember(50*(g-1)+b+1,this._register.getItem(d+b+1))},function(d,a,g){D.call(this,d,J,K)},function(d,g){for(var b=a.gc.createArray(),m=this._instructions,k=m.constructor.prototype,k=k.slice||k.subarray,c;void 0!==(c=m[4*this._pc])&&(0===c||4===c)&&0===this._instructions[4*this._pc+1];)b.push.apply(b,k.call(m,4*this._pc,4*this._pc+4)),this._pc++;b=new a.Function(this._vm,this._file,
this._functions[g],this._globals,B.call(this,g,b,L,u));this._register.setItem(d,b)},function(d,a){var g,b;b=0===a?Math.max(0,this._params.length-this._data.paramCount):a-1;for(g=0;g<b;g++)this._register.setItem(d+g,this._params[this._data.paramCount+g]);g=d+b;for(b=this._register.getLength();g<b;g++)this._register.clearItem(g)}];a.operations.NAMES="move loadk loadbool loadnil getupval getglobal gettable setglobal setupval settable newtable self add sub mul div mod pow unm not len concat jmp eq lt le test testset call tailcall return forloop forprep tforloop setlist close closure vararg".split(" ");
a.operations.evaluateInScope=function(d){a.getCurrentVM();eval("func="+d)};a.operations.internal={getglobal:b,gettable:c,setglobal:f,settable:h,newtable:e,self:l,binary_arithmetic:k,add:p,sub:q,mul:x,div:z,mod:r,unm:y,len:s,concat:d,eq:g,compare:t,call:H,tforloop:I,close:D,closure_upvalues:B,lt_func:E,le_func:F}})(shine||{});"use strict";
(function(a){function b(a){return"string"==typeof a?(a=a.replace(/\n/g,"\\n"),a=a.replace(/'/g,"\\'"),"'"+a+"'"):a}function c(a){a+=this.pc;this.vars.push(a);return a}function f(a,c,q,e){c=256<=c?b(this.getConstant(c-256)):"R["+c+"]";q=256<=q?b(this.getConstant(q-256)):"R["+q+"]";return"setR(R,"+a+",binary_arithmetic_internal("+c+","+q+",'__"+e+"',"+e+"_internal));"}function h(a,c,q,e,h){var f=this.pc+2;this.jumpDestinations[f]=1;c=256<=c?b(this.getConstant(c-256)):"R["+c+"]";q=256<=q?b(this.getConstant(q-
256)):"R["+q+"]";return"if(compare_internal("+c+","+q+",'"+e+"',"+h+")!="+a+"){pc="+f+";break;}"}function e(b,c,q){var e;if(0===c)e=b+1+",void 0";else if(1===c)e="void 0,void 0";else{e=b+1+","+(b+c);var h=!0,f,l=a.gc.createArray(),s;for(f=1;f<c;f++)if((s=this.code[this.pc-f])&&s.match(n)&&s[1]==""+(b+c-f))l.unshift(s[2]);else{h=!1;break}if(h&&(s=this.code[this.pc-c].match(n))&&s[1]==""+b){e=s[2];for(f=1;f<=c;f++)this.code[this.pc-f]="";return 1==q?e+".call(void 0,"+l.join(",")+");":"setRArr(R,"+b+
","+(q?q-1:"void 0")+","+e+".call(void 0,"+l.join(",")+"));"}}return"callR(R,"+b+","+q+","+e+");"}function l(a,b,c){0>this.vars.indexOf("getupval")&&this.vars.push("getupval");return"close_internal.call(cl,"+a+",getupval);"}a.jit=a.jit||{};a.jit.enabled=a.jit.enabled||!1;var n=/^setR\(R,(\d+),([^;]*?)\);$/;a.jit.TRANSLATORS=[function(a,b){return"setR(R,"+a+",R["+b+"]);"},function(a,c){return"setR(R,"+a+","+b(this.getConstant(c))+");"},function(a,b,c){a="setR(R,"+a+","+!!b+");";c&&(this.jumpDestinations[c=
this.pc+2]=1,a+="pc="+c+";break;");return a},function(a,b){for(var c=[],e=a;e<=b;e++)c.push("setR(R,"+e+");");return c.join("")},function(a,b){return"(cl._upvalues["+b+"]!==void 0)&&(setR(R,"+a+",cl._upvalues["+b+"].getValue()));"},function(a,c){var e=this.getConstant(c);return"setR(R,"+a+",shine_g"+("_G"==e?"":"["+b(e)+"]")+");"},function(a,c,e){e=256<=e?b(this.getConstant(e-256)):"R["+e+"]";return"setR(R,"+a+",gettable_internal(R["+c+"],"+e+"));"},function(a,c){return"setglobal_internal.call(cl,"+
b(this.getConstant(c))+",R["+a+"]);"},function(a,b){return"cl._upvalues["+b+"].setValue(R["+a+"]);"},function(a,c,e){c=256<=c?b(this.getConstant(c-256)):"R["+c+"]";e=256<=e?b(this.getConstant(e-256)):"R["+e+"]";return"settable_internal(R["+a+"],"+c+","+e+");"},function(a,b,c){return"setR(R,"+a+",newtable_internal());"},function(a,c,e){e=256<=e?b(this.getConstant(e-256)):"R["+e+"]";return"setR(R,"+(a+1)+",R["+c+"]);setR(R,"+a+",self_internal(R["+c+"],"+e+"));"},function(a,b,c){return f.call(this,a,
b,c,"add")},function(a,b,c){return f.call(this,a,b,c,"sub")},function(a,b,c){return f.call(this,a,b,c,"mul")},function(a,b,c){return f.call(this,a,b,c,"div")},function(a,b,c){return f.call(this,a,b,c,"mod")},function(a,c,e){c=256<=c?b(this.getConstant(c-256)):"R["+c+"]";e=256<=e?b(this.getConstant(e-256)):"R["+e+"]";return"setR(R,"+a+",binary_arithmetic_internal("+c+","+e+",'__pow',Math.pow));"},function(a,b){return"setR(R,"+a+",unm_internal(R["+b+"]));"},function(a,b){return"setR(R,"+a+",!R["+b+
"]);"},function(a,b){return"setR(R,"+a+",len_internal(R["+b+"]));"},function(a,b,c){return"setR(R,"+a+",concat_internal(R["+c+"],R.slice("+b+","+c+").reverse()));"},function(a,b){var c=this.pc+b+1;this.jumpDestinations[c]=1;return"pc="+c+";break;"},function(a,c,e){var f=this.pc+2;this.jumpDestinations[f]=1;a=a?"!":"";c=256<=c?b(this.getConstant(c-256)):"R["+c+"]";e=256<=e?b(this.getConstant(e-256)):"R["+e+"]";return"if("+a+"eq_internal("+c+","+e+")){pc="+f+";break}"},function(a,b,c){return h.call(this,
a,b,c,"__lt","lt_func")},function(a,b,c){return h.call(this,a,b,c,"__le","le_func")},function(a,b,c){b=this.pc+2;this.jumpDestinations[b]=1;return"if(shine.utils.coerceToBoolean(R["+a+"])!="+c+"){pc="+b+";break}"},function(a,b,c){var e=this.pc+2;this.jumpDestinations[e]=1;return"if(shine.utils.coerceToBoolean(R["+b+"])=="+c+"){R["+a+"]=R["+b+"]}else{pc="+e+";break}"},e,function(a,b){return e.call(this,a,b,0)},function(a,b){var e="",e=l.call(this,0);0===b?(c.call(this,"i"),e+="return R.slice("+a+");"):
e=1==b?e+"return createArray();":e+("return R.slice("+a+","+(a+b-1)+");");return e},function(a,b){var e="R["+(a+2)+"]",f="R["+(a+1)+"]",h="R["+a+"]+"+e,l=e+">0",n=c.call(this,"limit"),s=this.pc+b+1,d=!0,g;for(g=s;g<this.pc;g++)if(this.jumpDestinations[g]||this.code[g]&&0<=this.code[g].indexOf("pc=")){d=!1;break}if(d)return h="R["+(a+3)+"]",this.code[s-1]="for("+h+"=R["+a+"],"+n+"="+f+";"+h+(l?"<":">")+"="+n+";"+h+"+="+e+"){",delete this.jumpDestinations[this.pc],"}";this.jumpDestinations[s]=1;return"setR(R,"+
a+","+h+");_="+l+";if((_&&R["+a+"]<="+f+")||(!_&&R["+a+"]>="+f+")){setR(R,"+(a+3)+",R["+a+"]);pc="+s+";break}"},function(a,b){var c=this.pc+b+1;this.jumpDestinations[c]=1;return"setR(R,"+a+",R["+a+"]-R["+(a+2)+"]);pc="+c+";break;"},function(a,b,e){b=c.call(this,"tfor");var f=this.pc+2,h,l,n=this.pc+this._instructions[4*this.pc+6]+1;h=!0;for(l=n+1;l<this.pc;l++)if(this.jumpDestinations[l]||this.code[l]&&0<=this.code[l].indexOf("pc=")){h=!1;break}if(h){delete this.jumpDestinations[this.pc];this.code[this.pc+
1]="/* noop */";h="while(1){"+(b+"=tforloop_internal(R["+a+"],R.slice("+(a+1)+","+(a+3)+"));");for(l=0;l<e;l++)h+="setR(R,"+(a+l+3)+","+b+"["+l+"]);";this.code[n]=h+("if("+b+"[0]!==void 0){setR(R,"+(a+2)+","+b+"[0])}else{break}");return"}"}this.jumpDestinations[f]=1;h=b+"=tforloop_internal(R["+a+"],R.slice("+(a+1)+","+(a+3)+"));";for(l=0;l<e;l++)h+="setR(R,"+(a+l+3)+","+b+"["+l+"]);";return h+="if("+b+"[0]!==void 0){setR(R,"+(a+2)+","+b+"[0])}else{pc="+f+";break}"},function(a,b,c){return"setlistT(R,R["+
a+"],"+(a+1)+","+(50*(c-1)+1)+","+(0==b?"R.length-1":b)+");"},l,function(b,c){var e=a.gc.createArray(),h=this._instructions,f=h.constructor.prototype,f=f.slice||f.subarray||Array.prototype.slice,l;this.pc++;0>this.vars.indexOf("getupval")&&this.vars.push("getupval");for(0>this.vars.indexOf("setupval")&&this.vars.push("setupval");void 0!==(l=h[4*this.pc])&&(0===l||4===l)&&0===this._instructions[4*this.pc+1];)e.push.apply(e,f.call(h,4*this.pc,4*this.pc+4)),this.pc++;this.pc--;return e.length||"undefined"==
typeof process?"setR(R,"+b+",create_func(cl._functions["+c+"],closure_upvalues.call(cl,"+c+","+JSON.stringify(e)+",getupval,setupval),cl));":"setR(R,"+b+",cl._functions["+c+"]);"},function(a,b){var c="R.length="+a+";",e,h;if(0===b)c="for(_="+this.paramCount+";_<arguments.length;_++)setR(R,_+"+(a-this.paramCount)+",arguments[_]);";else for(e=0,h=b-1;e<h;e++)c+="setR(R,"+(a+e)+",arguments["+(this.paramCount+e)+"]);";return c}];a.jit.compile=function(b){b=a.jit.toJS(b);return a.operations.evaluateInScope(b)};
a.jit.toJS=function(b){var c=b._data.instructions,e=b._data.paramCount,h=[],h=0,f,l,n,s,d,g,m="",t;f={paramCount:e,isVararg:0<b._data.is_vararg,stackSize:b._data.maxStackSize,pc:h,code:[],vars:[],jumpDestinations:[1],_constants:b._data.constants,_instructions:b._data.instructions,getConstant:function(a){if(null!==this._constants[a])return this._constants[a]}};for(t=c.length/4;h<t;)d=4*h,l=c[d],n=c[d+1],s=c[d+2],d=c[d+3],f.code[h]||(f.code[h]=a.jit.TRANSLATORS[l].call(f,n,s,d)),h=++f.pc;for(h in f.jumpDestinations)c=
parseInt(h,10),f.code[c]="case "+h+":"+f.code[c];7==b._data.is_vararg&&(g="setR(R,"+e+",new shine.Table(Array.prototype.slice.call(arguments,"+e+")));R["+e+'].setMember("n", arguments.length-'+e+");");0<=f.vars.indexOf("getupval")&&(m+="getupval=get_upv.bind(R);");0<=f.vars.indexOf("setupval")&&(m+="setupval=set_upv.bind(R);");h=["/* "+(b._file&&b._file.url)+":"+b._data.lineDefined+" */","var cl=this,R=createArray(),pc=0,_"+(f.vars.length?","+f.vars.join(","):"")+";"];for(c=0;c<e;c++)h.push("setR(R,"+
c+",arguments["+c+"]);");g&&h.push(g);h.push(m);h.push("shine.Closure._current=cl;while(1){switch(pc){");h=h.concat(f.code);h.push("}}");return"function(){"+h.join("\n")+"}"}})(shine||{});"undefined"!=typeof module&&(module.exports=shine.jit);"use strict";
(function(a){function b(){y=n*y%k;return y/k}function c(d){if(d&&d instanceof a.VM)return d;d=a.getCurrentVM();if(!d)throw new a.Error("Can't call library function without passing a VM object as the context");return d}function f(d,g){if(void 0===g)throw new a.Error("Bad argument #2 to ipairs() iterator");var b=g+1,c=d.__shine.numValues;return c.hasOwnProperty(b)&&void 0!==c[b]?[b,c[b]]:void 0}function h(a,g,b){var c=parseInt(r["%j"](a),10);a=(8-(new Date(a.getFullYear(),0,1,12))["get"+(b?"UTC":"")+
"Day"]()+g)%7;return("0"+(Math.floor((c-a)/7)+1)).substr(-2)}function e(a){a=""+a;var g=0,b,c,e,h;for(b in p)p.hasOwnProperty(b)&&(a=a.replace(RegExp(b,"g"),p[b]));c=a.length;for(b=0;b<c;b++)e=a.substr(b,1),h=!1,"["==e?(g&&(h=!0),g++):"]"==e&&(g--,g&&(h=!0)),h&&(a=a.substr(0,b)+a.substr(b++ +1),c++);return a}function l(d,g){var b=c(this);b.fileManager.load(d,function(c,e){if(c)b._trigger("module-load-error",[e,c]),404==c&&/\.lua$/.test(d)?l.call(b,d+".json",g):g();else{var h=new a.Function(b,e,e.data,
b._globals);b._trigger("module-loaded",[e,h]);g(h)}});b._trigger("loading-module",d)}var n=16807,k=2147483647,p={"([^a-zA-Z0-9%(])-":"$1*?","(.)-([^a-zA-Z0-9?])":"$1*?$2","(.)-$":"$1*?","%a":"[a-zA-Z]","%A":"[^a-zA-Z]","%c":"[\x00-\u001f]","%C":"[^\x00-\u001f]","%d":"\\d","%D":"[^d]","%l":"[a-z]","%L":"[^a-z]","%p":"[.,\"'?!;:#$%&()*+-/<>=@[]\\^_{}|~]","%P":"[^.,\"'?!;:#$%&()*+-/<>=@[]\\^_{}|~]","%s":"[ \\t\\n\\f\\v\\r]","%S":"[^ \t\n\f\v\r]","%u":"[A-Z]","%U":"[^A-Z]","%w":"[a-zA-Z0-9]","%W":"[^a-zA-Z0-9]",
"%x":"[a-fA-F0-9]","%X":"[^a-fA-F0-9]","%([^a-zA-Z])":"\\$1"},q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" "),z=[31,28,31,30,31,30,31,31,30,31,30,31],r={"%a":function(a,g){return q[a["get"+(g?"UTC":"")+"Day"]()].substr(0,3)},"%A":function(a,g){return q[a["get"+(g?"UTC":"")+"Day"]()]},"%b":function(a,g){return x[a["get"+(g?"UTC":"")+"Month"]()].substr(0,3)},"%B":function(a,g){return x[a["get"+
(g?"UTC":"")+"Month"]()]},"%c":function(a,g){return a["to"+(g?"UTC":"")+"LocaleString"]()},"%d":function(a,g){return("0"+a["get"+(g?"UTC":"")+"Date"]()).substr(-2)},"%H":function(a,g){return("0"+a["get"+(g?"UTC":"")+"Hours"]()).substr(-2)},"%I":function(a,g){return("0"+((a["get"+(g?"UTC":"")+"Hours"]()+11)%12+1)).substr(-2)},"%j":function(a,g){for(var b=a["get"+(g?"UTC":"")+"Date"](),c=a["get"+(g?"UTC":"")+"Month"](),e=0;e<c;e++)b+=z[e];1<c&&0===a["get"+(g?"UTC":"")+"FullYear"]()%4&&(b+=1);return("00"+
b).substr(-3)},"%m":function(a,g){return("0"+(a["get"+(g?"UTC":"")+"Month"]()+1)).substr(-2)},"%M":function(a,g){return("0"+a["get"+(g?"UTC":"")+"Minutes"]()).substr(-2)},"%p":function(a,g){return 12>a["get"+(g?"UTC":"")+"Hours"]()?"AM":"PM"},"%S":function(a,g){return("0"+a["get"+(g?"UTC":"")+"Seconds"]()).substr(-2)},"%U":function(a,g){return h(a,0,g)},"%w":function(a,g){return""+a["get"+(g?"UTC":"")+"Day"]()},"%W":function(a,g){return h(a,1,g)},"%x":function(a,g){return r["%m"](a,g)+"/"+r["%d"](a,
g)+"/"+r["%y"](a,g)},"%X":function(a,g){return r["%H"](a,g)+":"+r["%M"](a,g)+":"+r["%S"](a,g)},"%y":function(a,g){return r["%Y"](a,g).substr(-2)},"%Y":function(a,g){return""+a["get"+(g?"UTC":"")+"FullYear"]()},"%Z":function(a,g){var b;return g&&"UTC"||(b=a.toString().match(/[A-Z][A-Z][A-Z]/))&&b[0]},"%%":function(){return"%"}},y=1,s;a.lib={assert:function(d,g){if(!1===d||void 0===d)throw new a.Error(g||"Assertion failed!");return[d,g]},collectgarbage:function(a,g){},dofile:function(a){},error:function(d){throw new a.Error(d);
},getfenv:function(a){},getmetatable:function(d){var g;if(d instanceof a.Table)return(g=d.__shine.metatable)&&(g=g.__metatable)?g:d.__shine.metatable;if("string"==typeof d)return s},ipairs:function(d){if(!((d||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in ipairs(). Table expected");return[f,d,0]},load:function(d,g){for(var b=c(this),e="",h;(h=d.apply(d))&&(h=h[0]);)e+=h;return a.lib.loadstring.call(b,e)},loadfile:function(a){var g=c(this);g.suspend();l.call(g,a,function(a){g.resume(a||
[])})},loadstring:function(d,g){var b=c(this);if("string"!=typeof d)throw new a.Error("bad argument #1 to 'loadstring' (string expected, got "+a.utils.coerce(d,"string")+")");if(!d)return new a.Function(b);b.suspend();b.fileManager.load(d,function(d,g){if(d)b.resume([]);else{var c=new a.Function(b,g,g.data,b._globals,a.gc.createArray());b.resume([c])}})},next:function(d,b){var c=void 0===b,e=d.__shine.numValues,h,f;if(c||"number"==typeof b&&0<b&&b==b>>0)if("keys"in Object){h=Object.keys(e);if(c)f=
1;else if(f=h.indexOf(""+b)+1)c=!0;if(c&&void 0!==(f=h[f]))return[f>>=0,e[f]]}else for(h in e)if(f=h>>0,!c)f===b&&(c=!0);else if(void 0!==e[f])return[f,e[f]];for(f in d)if(d.hasOwnProperty(f)&&!(f in a.Table.prototype)&&"__shine"!==f)if(!c)f==b&&(c=!0);else if(d.hasOwnProperty(f)&&void 0!==d[f]&&"__"!=(""+f).substr(0,2))return[f,d[f]];for(f in d.__shine.keys)if(d.__shine.keys.hasOwnProperty(f))if(e=d.__shine.keys[f],!c)e===b&&(c=!0);else if(void 0!==d.__shine.values[f])return[e,d.__shine.values[f]];
return a.gc.createArray()},pairs:function(d){if(!((d||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in pairs(). Table expected");return[a.lib.next,d]},pcall:function(d){for(var b=a.gc.createArray(),c,e=1,h=arguments.length;e<h;e++)b.push(arguments[e]);try{if("function"==typeof d)c=d.apply(null,b);else if((d||a.EMPTY_OBJ)instanceof a.Function)c=d.apply(null,b,!0);else throw new a.Error("Attempt to call non-function");}catch(f){return[!1,f&&f.message||f]}(c||a.EMPTY_OBJ)instanceof
Array||(c=[c]);c.unshift(!0);return c},print:function(){for(var d=a.gc.createArray(),b=0,c=arguments.length;b<c;b++)d.push(a.lib.tostring(arguments[b]));return a.stdout.write(d.join("\t"))},rawequal:function(a,b){return a===b},rawget:function(d,b){if(!((d||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in rawget(). Table expected");return d[b]},rawset:function(d,b,c){if(!((d||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in rawset(). Table expected");if(void 0==
b)throw new a.Error("Bad argument #2 in rawset(). Nil not allowed");d[b]=c;return d},require:function(d){function b(a){return function(){return e(a)}}function e(c){var m;f._resumeStack.length?m=f._resumeStack.pop()._run():a.debug&&a.debug._resumeStack.length?m=a.debug._resumeStack.pop()._run():(k.loaded[d]=!0,m=c.call(null,d));if(f._status==a.SUSPENDING&&!m)n._pc--,f._resumeStack.push(b(c));else if(a.debug&&a.debug._status==a.SUSPENDING&&!m)n._pc--,a.debug._resumeStack.push(b(c));else if(m)return q=
m[0],void 0!==q&&k.loaded.setMember(d,q),k.loaded[d]}function h(){if(s=r.shift())s=s.replace(/\?/g,d.replace(/\./g,"/")),l.call(f,s,function(b){b?(k.preload[d]=b,a.Closure._current._pc--,f.resume()):(B.push("\tno file '"+s+"'"),h())});else throw new a.Error("module '"+d+"' not found:\n\tno field package.preload['"+d+"']\n"+B.join("\n"));}var f=c(this),k=f._globals["package"],n=a.Closure._current,q,p,r,s,x,B=a.gc.createArray();d=a.utils.coerceToString(d);if(q=k.loaded[d])return q;if(p=k.preload[d])return e(p);
p=d.replace(/\./g,"/")+".lua.json";if(x=f.fileManager._cache[p])return p=new a.File(p,x),p=new a.Function(f,p,p.data,f._globals),k.preload[d]=p,e(p);r=k.path.replace(/;;/g,";").split(";");f.suspend();h()},select:function(d){a.gc.createArray();if("#"==d)return arguments.length-1;if(d=parseInt(d,10))return arguments.constructor===Array?arguments.slice(d):Array.prototype.slice.call(arguments,d);throw new a.Error('bad argument #1 in select(). Number or "#" expected');},setmetatable:function(d,b){var c;
if(!((d||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in setmetatable(). Table expected");if(!(void 0===b||(b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #2 in setmetatable(). Nil or table expected");if((c=d.__shine.metatable)&&c.__metatable)throw new a.Error("cannot change a protected metatable");a.gc.incrRef(b);a.gc.decrRef(d.__shine.metatable);d.__shine.metatable=b;return d},tonumber:function(d,b){var c;if(""!==d){b=b||10;if(2>b||36<b)throw new a.Error("bad argument #2 to tonumber() (base out of range)");
if(10==b&&(Infinity===d||-Infinity===d||"number"==typeof d&&window.isNaN(d)))return d;if(10!=b&&void 0==d)throw new a.Error("bad argument #1 to 'tonumber' (string expected, got nil)");d=(""+d).replace(/^\s+|\s+$/g,"");if(10==b)return a.utils.coerceToNumber(d);d=a.utils.coerceToString(d);16==b&&(c=d.match(/^(\-)?0[xX](.+)$/))&&(d=(c[1]||"")+c[2]);c=RegExp("^["+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".substr(0,b)+"]*$","gi");if(c.test(d))return parseInt(d,b)}},tostring:function(d){var b,c;return void 0!==
d&&d instanceof a.Table&&(b=d.__shine.metatable)&&(c=b.getMember("__tostring"))?c.call(c,d):d&&(d instanceof a.Table||d instanceof a.Function)?d.toString():"function"==typeof d?"function: [host code]":a.utils.coerceToString(d)||"userdata"},type:function(d){var b=typeof d;switch(b){case "undefined":return"nil";case "number":case "string":case "boolean":case "function":return b;case "object":return d.constructor===a.Table?"table":(d||a.EMPTY_OBJ)instanceof a.Function?"function":"userdata"}},unpack:function(d,
b,c){return a.lib.table.unpack(d,b,c)},_VERSION:"Lua 5.1",xpcall:function(d,b){var c,e,f;try{"function"==typeof d?c=d.apply():(d||a.EMPTY_OBJ)instanceof a.Function?c=d.apply(null,void 0,!0):f=!0,e=!0}catch(h){c=b.apply(null,void 0,!0),(c||a.EMPTY_OBJ)instanceof Array&&(c=c[0]),e=!1}if(f)throw new a.Error("Attempt to call non-function");(c||a.EMPTY_OBJ)instanceof Array||(c=[c]);c.unshift(e);return c}};a.lib.coroutine=new a.Table({create:function(d){return a.Coroutine.create(d)},resume:function(d){if(2>
arguments.length)return d.resume.call(d);for(var b=a.gc.createArray(),c=1,e=arguments.length;c<e;c++)b.push(arguments[c]);return d.resume.apply(d,b)},running:function(){return c(this)._coroutineRunning},status:function(d){switch(d.status){case a.RUNNING:return d===c()._coroutineRunning?"running":"normal";case a.SUSPENDED:return"suspended";case a.DEAD:return"dead"}},wrap:function(d){var b=a.lib.coroutine.create(d),e=c(this);d=function(){for(var d=[b],c=0,f=arguments.length;c<f;c++)d.push(arguments[c]);
if((d=a.lib.coroutine.resume.apply(null,d))||!(e._status==a.SUSPENDING||a.debug&&a.debug._status==a.SUSPENDING)){if(c=d.shift())return d;throw d[0];}};d._coroutine=b;return d},yield:function(){var d=c()._coroutineRunning,b;if(!d)throw new a.Error("attempt to yield across metamethod/C-call boundary (not in coroutine)");if(d.status!=a.RUNNING)throw new a.Error("attempt to yield non-running coroutine in host");b=a.gc.createArray();for(var e=0,f=arguments.length;e<f;e++)b.push(arguments[e]);d._yieldVars=
b;d.status=a.SUSPENDING;return{resume:function(){var b=[d],g,c=arguments.length,e=function(){a.lib.coroutine.resume.apply(void 0,b)};1==arguments.length&&void 0===arguments[0]&&(c=0);for(g=0;g<c;g++)b.push(arguments[g]);d.status==a.SUSPENDING?window.setTimeout(e,1):e()}}}});a.lib.debug=new a.Table({debug:function(){},getfenv:function(a){},gethook:function(a){},getinfo:function(a,b,c){},getlocal:function(a,b,c){},getmetatable:function(a){},getregistry:function(){},getupvalue:function(a,b){},setfenv:function(a,
b){},sethook:function(a,b,c,e){},setlocal:function(a,b,c,e){},setmetatable:function(a,b){},setupvalue:function(a,b,c){},traceback:function(a,b,c){}});a.lib.io=new a.Table({close:function(d){if(d)throw new a.Error("File operations currently not supported.");},flush:function(){},input:function(d){throw new a.Error("File operations currently not supported.");},lines:function(d){throw new a.Error("File operations currently not supported.");},open:function(d){throw new a.Error("File operations currently not supported.");
},output:function(d){throw new a.Error("File operations currently not supported.");},popen:function(d,b){throw new a.Error("File operations currently not supported.");},read:function(){throw new a.Error("File operations currently not supported.");},stderr:{},stdin:{},stdout:{},tmpfile:function(){throw new a.Error("File operations currently not supported.");},type:function(){},write:function(){var d,b="";for(d in arguments)arguments.hasOwnProperty(d)&&(b+=a.utils.coerceToString(arguments[d],"bad argument #"+
d+" to 'write' (string expected, got %type)"));a.stdout.write(b)}});a.lib.math=new a.Table({abs:function(a){return Math.abs(a)},acos:function(a){return Math.acos(a)},asin:function(a){return Math.asin(a)},atan:function(a){return Math.atan(a)},atan2:function(a,b){return Math.atan2(a,b)},ceil:function(a){return Math.ceil(a)},cos:function(a){return Math.cos(a)},cosh:function(d){var b=a.lib.math.exp;return(b(d)+b(-d))/2},deg:function(a){return 180*a/Math.PI},exp:function(a){return Math.exp(a)},floor:function(a){return Math.floor(a)},
fmod:function(a,b){return a%b},frexp:function(a){var b,c;if(0==a)return[0,0];b=0<a?1:-1;a*=b;c=Math.floor(Math.log(a)/Math.log(2))+1;return[a/Math.pow(2,c)*b,c]},huge:Infinity,ldexp:function(a,b){return a*Math.pow(2,b)},log:function(a,b){var c=Math.log(a);return void 0!==b?c/Math.log(b):c},log10:function(a){return Math.log(a)/Math.log(10)},max:function(){return Math.max.apply(Math,arguments)},min:function(){return Math.min.apply(Math,arguments)},modf:function(a){var b=Math.floor(a);return[b,a-b]},
pi:Math.PI,pow:function(b,c){var e=a.utils.coerceToNumber;b=e(b,"bad argument #1 to 'pow' (number expected)");c=e(c,"bad argument #2 to 'pow' (number expected)");return Math.pow(b,c)},rad:function(b){b=a.utils.coerceToNumber(b,"bad argument #1 to 'rad' (number expected)");return Math.PI/180*b},random:function(d,c){if(void 0===d&&void 0===c)return b();if("number"!==typeof d)throw new a.Error("bad argument #1 to 'random' (number expected)");if(void 0===c)c=d,d=1;else if("number"!==typeof c)throw new a.Error("bad argument #2 to 'random' (number expected)");
if(d>c)throw new a.Error("bad argument #2 to 'random' (interval is empty)");return Math.floor(b()*(c-d+1)+d)},randomseed:function(b){if("number"!==typeof b)throw new a.Error("bad argument #1 to 'randomseed' (number expected)");y=b},sin:function(a){return Math.sin(a)},sinh:function(b){var c=a.lib.math.exp;return(c(b)-c(-b))/2},sqrt:function(a){return Math.sqrt(a)},tan:function(a){return Math.tan(a)},tanh:function(b){var c=a.lib.math.exp;return(c(b)-c(-b))/(c(b)+c(-b))}});a.lib.os=new a.Table({clock:function(){},
date:function(b,c){void 0===b&&(b="%c");var e,f=new Date;c&&f.setTime(1E3*c);"!"===b.substr(0,1)&&(b=b.substr(1),e=!0);if("*t"===b){var h=a.Table,k=parseInt(r["%Y"](f,e),10),l=parseInt(r["%m"](f,e),10),n=parseInt(r["%d"](f,e),10),q=parseInt(r["%H"](f,e),10),p=parseInt(r["%M"](f,e),10),s=parseInt(r["%S"](f,e),10),x=parseInt(r["%w"](f,e),10)+1;e=parseInt(r["%j"](f,e),10);var B=f.getFullYear(),B=new Date(B,0),f=f.getTimezoneOffset()!==B.getTimezoneOffset();return new h({year:k,month:l,day:n,hour:q,min:p,
sec:s,wday:x,yday:e,isdst:f})}for(h in r)r.hasOwnProperty(h)&&0<=b.indexOf(h)&&(b=b.replace(h,r[h](f,e)));return b},difftime:function(a,b){return a-b},execute:function(){if(arguments.length)throw new a.Error("shell is not available. You should always check first by calling os.execute with no parameters");return 0},exit:function(b){throw new a.Error("Execution terminated ["+(b||0)+"]");},getenv:function(){},remove:function(){},rename:function(){},setlocale:function(){},time:function(b){if(b){var c,
e,f,h,k,l;if(!(c=b.getMember("day")))throw new a.Error("Field 'day' missing in date table");if(!(e=b.getMember("month")))throw new a.Error("Field 'month' missing in date table");if(!(f=b.getMember("year")))throw new a.Error("Field 'year' missing in date table");h=b.getMember("hour")||12;k=b.getMember("min")||0;l=b.getMember("sec")||0;b.getMember("isdst")&&h--;b=(new Date(f,e-1,c,h,k,l)).getTime()}else b=Date.now?Date.now():(new Date).getTime();return Math.floor(b/1E3)},tmpname:function(){}});a.lib["package"]=
new a.Table({cpath:void 0,loaded:new a.Table,loadlib:function(a,b){},path:"?.lua.json;?.json;modules/?.lua.json;modules/?.json;modules/?/?.lua.json;modules/?/index.lua.json",preload:{},seeall:function(b){var g=c(this),e=new a.Table;e.setMember("__index",g._globals);a.lib.setmetatable(b,e)}});a.lib.string=new a.Table({"byte":function(b,c,e){c=c||1;e=e||c;for(var f=a.gc.createArray(),h=b.length;c<=h&&c<=e;c++)f.push(b.charCodeAt(c-1)||void 0);return f},"char":function(){for(var a="",b=0,c=arguments.length;b<
c;b++)a+=String.fromCharCode(arguments[b]);return a},dump:function(b){b=b._data;var c=a.gc.createObject(),e=a.gc.createArray(),f;for(f in b)b.hasOwnProperty(f)&&(c[f]=b[f]);e.push.apply(e,c.instructions);c.instructions=e;return JSON.stringify(c)},find:function(b,c,f,h){if("string"!=typeof b&&"number"!=typeof b)throw new a.Error("bad argument #1 to 'find' (string expected, got "+typeof b+")");if("string"!=typeof c&&"number"!=typeof c)throw new a.Error("bad argument #2 to 'find' (string expected, got "+
typeof c+")");b=""+b;f=f||1;if(void 0===h||!h){c=e(c);c=RegExp(c);h=b.substr(f-1).search(c);if(0>h)return;b=b.substr(f-1).match(c);f=[h+f,h+f+b[0].length-1];b.shift();return f.concat(b)}h=b.indexOf(c,f-1);return-1===h?void 0:[h+1,h+c.length]},format:function(b){function c(b){var d=b[2],g=parseInt(b[5]);if(5<(""+d).length)throw new a.Error("invalid format (repeated flags)");g||0===g||(g=Infinity);return{showSign:0<=d.indexOf("+"),prefix:0<=d.indexOf(" "),leftAlign:0<=d.indexOf("-"),alternateForm:0<=
d.indexOf("#"),zeroPad:0<=d.indexOf("0"),minWidth:parseInt(b[3])||0,hasPrecision:!!b[4],precision:g}}function e(a,b){return Array(b+1).join(a)}function f(a,b,d){var c;d.zeroPad&&!d.leftAlign&&0<(c=d.minWidth-a.length)&&((b||d.showSign||d.prefix)&&c--,a=e("0",c)+a);b?a="-"+a:d.showSign?a="+"+a:d.prefix&&(a=" "+a);return 0<(c=d.minWidth-a.length)?d.leftAlign?a+e(" ",c):e(" ",c)+a:a}function h(b){b=a.utils.coerceToNumber(b,"bad argument #"+z+" to 'format' (number expected)");return String.fromCharCode(b)}
function k(b){b=a.utils.coerceToNumber(b,"bad argument #"+z+" to 'format' (number expected)");var d=c(v),h=0>b,l;b=""+Math.floor(Math.abs(b));d.hasPrecision&&(Infinity!==d.precision&&0<(l=d.precision-b.length)&&(b=e("0",l)+b),d.zeroPad=!1);return f(b,h,d)}function l(b){b=a.utils.coerceToNumber(b,"bad argument #"+z+" to 'format' (number expected)");var d=c(v),h=0>b,k=b-Math.floor(b),n=Infinity===d.precision?6:d.precision;b=""+Math.floor(Math.abs(b));0<n&&(k=Math.round(k*Math.pow(10,n)),n-=(""+k).length,
b+="."+k+(n?e("0",n):""));return f(b,h,d)}function n(b,d){b=a.utils.coerceToNumber(b,"bad argument #"+z+" to 'format' (number expected)");var f=0>b;d=Math.pow(2,32);var h=c(v),k;b=Math.floor(b);f&&(b=d+b);b=b.toString(16);h.hasPrecision&&Infinity!==h.precision&&0<(k=h.precision-b.length)&&(b=e("0",k)+b);return 0<(k=h.minWidth-b.length)?h.leftAlign?b+e(" ",k):e(" ",k)+b:b}function q(b){b=a.utils.coerceToString(b);return'"'+b.replace(/([\n"])/g,"\\$1")+'"'}function p(b){var d=c(v),f;b=a.utils.coerceToString(b);
b=b.substr(0,d.precision);return 0<(f=d.minWidth-b.length)?d.leftAlign?b+e(" ",f):e(d.zeroPad?"0":" ",f)+b:b}function r(b){b=a.utils.coerceToNumber(b,"bad argument #"+z+" to 'format' (number expected)");var d=0>b,h=Math.pow(2,32),k=c(v),l;b=Math.floor(b);d&&(b=h+b);b=b.toString(16);d&&(b=e("f",8)+b);k.hasPrecision&&Infinity!==k.precision&&0<(l=k.precision-b.length)&&(b=e("0",l)+b);k.alternateForm&&(b="0x"+b);k.showSign=k.prefix=!1;k.zeroPad=k.zeroPad&&k.hasPrecision;return b=f(b,!1,k)}var s=/^((.|\s)*?)(%)((.|\s)*)$/,
x=/^(%?)([+\-#\ 0]*)(\d*)(\.(\d*))?([cdeEfgGiouqsxX])((.|\s)*)$/,y,u="",v,A=arguments.constructor===Array?arguments:Array.prototype.slice.call(arguments,0),z=2,C=2;for(A.shift();y=(""+b).match(s);){for(u+=y[1];"%"!=y[C];)C++;v=(""+y[C+1]).match(x);if(v[1])u+="%"+v[2]+v[3]+(v[4]||"")+v[6];else switch(v[6]){case "c":u+=h(A.shift());break;case "d":u+=k(A.shift());break;case "f":u+=l(A.shift());break;case "q":u+=q(A.shift());break;case "o":u+=n(A.shift());break;case "s":u+=p(A.shift());break;case "x":u+=
r(A.shift());break;case "X":u+=r(A.shift()).toUpperCase()}b=v[7];z++}return u+b},gmatch:function(a,b){b=e(b);var c=(""+a).match(RegExp(b,"g"));return function(){var a=c.shift(),d=RegExp(b).exec(a);if(void 0!==a)return d.shift(),d.length?d:a}},gsub:function(b,c,f,h){if("string"!=typeof b&&"number"!=typeof b)throw new a.Error("bad argument #1 to 'gsub' (string expected, got "+typeof b+")");if("string"!=typeof c&&"number"!=typeof c)throw new a.Error("bad argument #2 to 'gsub' (string expected, got "+
typeof c+")");if(void 0!==h&&void 0===(h=a.utils.coerceToNumber(h)))throw new a.Error("bad argument #4 to 'gsub' (number expected, got "+typeof h+")");b=""+b;c=e(""+c);for(var k=0,l="",n,q,p,r;(void 0===h||k<h)&&b&&(p=b.match(c));)"function"==typeof f||(f||a.EMPTY_OBJ)instanceof a.Function?(n=f.apply(null,[p[0]],!0),n instanceof Array&&(n=n[0]),void 0===n&&(n=p[0])):n=(f||a.EMPTY_OBJ)instanceof a.Table?f.getMember(p[0]):"object"==typeof f?f[p]:(""+f).replace(/%([0-9])/g,function(a,b){return p[b]}),
q=0==p[0].length&&void 0===r?"":b.split(p[0],1)[0],r=p[0],l+=q+n,b=b.substr((q+r).length),k++;return[l+b,k]},len:function(b){b=a.utils.coerceToString(b,"bad argument #1 to 'len' (string expected, got %type)");return b.length},lower:function(b){if("string"!=typeof b&&"number"!=typeof b)throw new a.Error("bad argument #1 to 'lower' (string expected, got "+typeof b+")");return(""+b).toLowerCase()},match:function(b,c,f){if("string"!=typeof b&&"number"!=typeof b)throw new a.Error("bad argument #1 to 'match' (string expected, got "+
typeof b+")");if("string"!=typeof c&&"number"!=typeof c)throw new a.Error("bad argument #2 to 'match' (string expected, got "+typeof c+")");b=(""+b).substr(f?f-1:0);if(b=b.match(RegExp(e(c)))){if(!b[1])return b[0];b.shift();return b}},rep:function(a,b){var c="",e;for(e=0;e<b;e++)c+=a;return c},reverse:function(a){var b="",c;for(c=a.length;0<=c;c--)b+=a.charAt(c);return b},sub:function(b,c,e){if("string"!=typeof b&&"number"!=typeof b)throw new a.Error("Bad argument #1 to 'sub' (string expected, got "+
typeof b+")");b=""+b;c=c||1;e=e||b.length;0<c?c-=1:0>c&&(c=b.length+c);0>e&&(e=b.length+e+1);return b.substring(c,e)},upper:function(a){return a.toUpperCase()}});s=new a.Table({__index:a.lib.string});a.lib.table=new a.Table({concat:function(b,c,e,f){if(!((b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 to 'concat' (table expected)");c=c||"";e=e||1;f=f||a.lib.table.maxn(b);return a.gc.createArray().concat(b.__shine.numValues).splice(e,f-e+1).join(c)},getn:function(b){if(!((b||
a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in 'getn' (table expected)");b=b.__shine.numValues;var c=a.gc.createArray(),e,f=0;for(e in b)b.hasOwnProperty(e)&&(c[e]=!0);for(;c[f+1];)f++;if(0<f&&void 0===b[f]){for(e=0;1<f-e;)c=Math.floor((e+f)/2),void 0===b[c]?f=c:e=c;return e}return f},insert:function(b,c,e){if(!((b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in table.insert(). Table expected");void 0==e?(e=c,c=b.__shine.numValues.length):c=a.utils.coerceToNumber(c,
"Bad argument #2 to 'insert' (number expected)");b.__shine.numValues.splice(c,0,void 0);b.setMember(c,e)},maxn:function(b){if(!((b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 to 'maxn' (table expected)");return b.__shine.numValues.length-1},remove:function(b,c){if(!((b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 in table.remove(). Table expected");var e=a.lib.table.getn(b),f=b.__shine.numValues,h;if(!(c>e)){void 0==c&&(c=e);for(h=f.splice(c,1);c<e&&
void 0===f[c];)delete f[c++];return h}},sort:function(b,c){if(!((b||a.EMPTY_OBJ)instanceof a.Table))throw new a.Error("Bad argument #1 to 'sort' (table expected)");var e,f=b.__shine.numValues;if(c){if(!(c instanceof a.Function||c.constructor===Function))throw new a.Error("Bad argument #2 to 'sort' (function expected)");e=function(a,b){return c.apply(null,[a,b],!0)[0]?-1:1}}else e=function(a,b){return a<b?-1:1};f.shift();f.sort(e).unshift(void 0)},unpack:function(b,c,e){if(!((b||a.EMPTY_OBJ)instanceof
a.Table))throw new a.Error("Bad argument #1 to 'unpack' (table expected)");c=c||1;void 0===e&&(e=a.lib.table.getn(b));for(var f=a.gc.createArray();c<=e;c++)f.push(b.getMember(c));return f}})})(shine||{});"use strict";
(function(a){function b(b,c){if(c)throw c=(""+c).replace(/\%type/gi,a.lib.type(b)),new a.Error(c);}function c(b){for(var f in b)b.hasOwnProperty(f)&&("object"===typeof b[f]?b[f]=c(b[f]):null===b[f]&&(b[f]=void 0));return new a.Table(b)}var f=/^[-+]?[0-9]*\.?([0-9]+([eE][-+]?[0-9]+)?)?$/,h=/^(\-)?0x([0-9a-fA-F]*)\.?([0-9a-fA-F]*)$/;a.utils={coerceToBoolean:function(a,b){return!(!1===a||void 0===a)},coerceToString:function(a,c){switch(!0){case "string"==typeof a:return a;case void 0===a:case null===
a:return"nil";case Infinity===a:return"inf";case -Infinity===a:return"-inf";case "number"==typeof a:case "boolean"==typeof a:return window.isNaN(a)?"nan":""+a;default:return b(a,c)||""}},coerceToNumber:function(a,c){var n,k,p;switch(!0){case "number"==typeof a:return a;case void 0===a:break;case "inf"===a:return Infinity;case "-inf"===a:return-Infinity;case "nan"===a:return NaN;default:if((""+a).match(f))n=parseFloat(a);else if(k=(""+a).match(h))if(p=k[3],(n=k[2])||p)n=parseInt(n,16)||0,p&&(n+=parseInt(p,
16)/Math.pow(16,p.length)),k[1]&&(n*=-1);void 0===n&&b(a,c);return n}},toObject:function(b){var c=0<a.lib.table.getn(b),c=a.gc["create"+(c?"Array":"Object")](),f=b.__shine.numValues,h,p=f.length;for(h=1;h<p;h++)c[h-1]=(f[h]||a.EMPTY_OBJ)instanceof a.Table?a.utils.toObject(f[h]):f[h];for(h in b)!b.hasOwnProperty(h)||h in a.Table.prototype||"__shine"===h||(c[h]=(b[h]||a.EMPTY_OBJ)instanceof a.Table?a.utils.toObject(b[h]):b[h]);return c},parseJSON:function(a){return c(JSON.parse(a))},get:function(b,
c,f){var h=new XMLHttpRequest,p;h.open("GET",b,!0);"ArrayBuffer"in window?(h.responseType="arraybuffer",p=function(a){if(1E4>=a.byteLength)return String.fromCharCode.apply(String,Array.prototype.slice.call(new Uint8Array(a)));var b,c=new Uint8Array(a),e="";b=0;for(a=a.byteLength;b<a;b+=1E4)e+=String.fromCharCode.apply(String,Array.prototype.slice.call(c.subarray(b,Math.min(b+1E4,a))));return e}):(h.responseType="text",p=function(a){return a});h.onload=function(a){200==this.status?c&&c(p(this.response)):
f&&f(this.status)};h.send(a.EMPTY_OBJ)}}})(shine||{});"use strict";(function(a){a.stdout={};a.stdout.write=function(a){console&&console.log?console.log(a):trace&&trace(a)};a.stddebug={};a.stddebug.write=function(a){};a.stderr={};a.stderr.write=function(a,c){c=c||"error";if(console&&console[c])console[c](a)}})(shine||{});var module=module;"undefined"!=typeof module&&(module.exports=shine);

});